FROM dddmr:x64

#install cuda 12.6
#see: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
RUN mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
RUN /bin/bash -c "cd /tmp && wget https://developer.download.nvidia.com/compute/cuda/12.6.3/local_installers/cuda-repo-ubuntu2204-12-6-local_12.6.3-560.35.05-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && dpkg -i cuda-repo-ubuntu2204-12-6-local_12.6.3-560.35.05-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && cp /var/cuda-repo-ubuntu2204-12-6-local/cuda-*-keyring.gpg /usr/share/keyrings/"
RUN /bin/bash -c "apt-get update"
RUN /bin/bash -c "apt-get -y install cuda-toolkit-12-6"

#install cudnn 9.6
#see: https://developer.nvidia.com/cudnn-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local
RUN /bin/bash -c "cd /tmp && wget https://developer.download.nvidia.com/compute/cudnn/9.6.0/local_installers/cudnn-local-repo-ubuntu2204-9.6.0_1.0-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && dpkg -i cudnn-local-repo-ubuntu2204-9.6.0_1.0-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && cp /var/cudnn-local-repo-ubuntu2204-9.6.0/cudnn-*-keyring.gpg /usr/share/keyrings/"
RUN /bin/bash -c "apt-get update"
RUN /bin/bash -c "apt-get -y install cudnn"

#install pytorch
RUN pip3 install pip-versions
RUN pip-versions list torch
RUN pip3 install torch==2.8.0
RUN pip3 install torchvision==0.23.0
RUN pip3 install torchaudio==2.8.0
RUN /bin/bash -c "export PATH=${PATH}:/usr/local/cuda/bin && export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda/lib64 && pip3 install pycuda==2024.1.2"
RUN /bin/bash -c "echo 'export PATH=\${PATH}:/usr/local/cuda/bin' >> ~/.bashrc"
RUN /bin/bash -c "echo 'export LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:/usr/local/cuda/lib64' >> ~/.bashrc"

#install tensorrt for c++ API
#see: https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html
#see for download: https://developer.nvidia.com/tensorrt/download/10x
RUN /bin/bash -c "cd /tmp && wget https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/10.7.0/local_repo/nv-tensorrt-local-repo-ubuntu2204-10.7.0-cuda-12.6_1.0-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && dpkg -i nv-tensorrt-local-repo-ubuntu2204-10.7.0-cuda-12.6_1.0-1_amd64.deb"
RUN /bin/bash -c "cd /tmp && cp /var/nv-tensorrt-local-repo-ubuntu2204-10.7.0-cuda-12.6/*-keyring.gpg /usr/share/keyrings/ && apt-get update"
RUN apt-get install -y tensorrt
#install tensorrt python
RUN python3 -m pip install tensorrt==10.7.0
RUN python3 -m pip install onnx==1.17.0

#TODO install customized opencv 
RUN pip3 install matplotlib

#install cv2
WORKDIR /usr/local/src 
# OpenCV
ARG OPENCV_VERSION=4.11.0
RUN curl -L -o opencv.zip https://github.com/opencv/opencv/archive/refs/tags/$OPENCV_VERSION.zip\
    && curl -L -o opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/refs/tags/$OPENCV_VERSION.zip\
    && unzip opencv.zip && unzip opencv_contrib.zip && cd opencv-$OPENCV_VERSION && mkdir build \
    && cd .. && rm opencv.zip opencv_contrib.zip

#GSTREAMER/gtk for opencv
RUN apt-get install -y flex bison meson
RUN apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev
RUN apt install -y libgtk-3-dev

#GSTREAMER/gtk for opencv
RUN apt-get install -y flex bison meson
RUN apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev
RUN apt install -y libgtk-3-dev

# check this for your gpu: https://developer.nvidia.com/cuda-gpus
ARG CUDA_ARCH
WORKDIR opencv-$OPENCV_VERSION/build
RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local/opencv$OPENCV_VERSION \
    -D ENABLE_FAST_MATH=1 \
    -D CUDA_FAST_MATH=1 \
    -D WITH_CUBLAS=1 \
    -D WITH_CUDA=ON \
    -D BUILD_opencv_cudacodec=OFF \
    -D WITH_OPENMP=ON \
    -D WITH_PNG=ON -D WITH_JPEG=ON -D WITH_TIFF=ON -D WITH_WEBP=OFF -D WITH_OPENJPEG=OFF \
    -D WITH_V4L=OFF -D WITH_JASPER=OFF -D WITH_OPENEXR=OFF -D WITH_FFMPEG=ON -D WITH_GTK=ON \
    -D WITH_QT=OFF -D WITH_GSTREAMER=ON -D BUILD_opencv_hdf=OFF \
    -D BUILD_TESTS=OFF -D BUILD_opencv_apps=OFF -D BUILD_PERF_TESTS=OFF \
    -D BUILD_opencv_python3=ON \
    -D OPENCV_PYTHON3_INSTALL_PATH=/usr/lib/python3/dist-packages \
    -D PYTHON_EXECUTABLE=/usr/bin/python3 \
    -D OPENCV_EXTRA_MODULES_PATH=/usr/local/src/opencv_contrib-$OPENCV_VERSION/modules \
    -D CUDA_BIN_PATH=/usr/local/cuda\
    -D CUDA_ARCH_BIN=${CUDA_ARCH}\
    ..\
    && make -j$(nproc) && make install

WORKDIR /root
CMD ["bash"]
